name: bob
version: 1.4.0.8

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src
  dependencies:
    - extra

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - hspec
