name: wordy
version: 1.5.0.8

dependencies:
  - base

library:
  exposed-modules: WordProblem
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - text
  - attoparsec

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - wordy
      - hspec
